INF = 987654321


MARKET_PRICE_ERROR = INF; INF+=1

KOSPI_CODE = '0'
KOSDAQ_CODE = '10'



""" 
    TR
"""
ORDER_CODES= ('KOA_NORMAL_BUY_KP_ORD', 'KOA_NORMAL_SELL_KP_ORD',
                'KOA_NORMAL_KP_CANCEL', 'KOA_NORMAL_KP_MODIFY',
                'KOA_NORMAL_BUY_KQ_ORD', 'KOA_NORMAL_SELL_KQ_ORD',
                'KOA_NORMAL_KQ_CANCEL', 'KOA_NORMAL_KQ_MODIFY')
TR_ACCOUNT = "opw00018"
TR_DEPOSIT = "opw00001"
TR_DAY_CHART = "opt10081"
TR_MINUTE_CHART = "opt10080"
TR_CURRENT_PRICE = "opt10001"


"""
    err code
"""
NO_ERROR = "0"


"""
    SCREEEN
"""

SCR_BUY = "0001"
SCR_SELL = "0002"
SCR_BUY_CANCEL = "0003"
SCR_SELL_CANCEL = "0004"
SCR_TR = "0005"
SCR_REAL_PRICE = "0006"
SCR_REAL_MARKET_TIME = "0007"

"""
    market state
"""
MARKET_YET = '0'
MARKET_OPEN= '3'
MARKET_CLOSE_SOON = '2'
MARKET_END = '4'
